name: Stop Review
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      head_ref:
        description: "Branch where review environment was created from (as in GitHub). Has to give as branch is probably removed and not available at the list."
        required: true
      pr_number:
        description: "Pull request number of the environment creator"

env:
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}

jobs:
  stop_review:
    runs-on: ubuntu-latest
    name: Stop Review
    steps:
      - uses: andersinno/kolga-setup-action@v2
        with:
          head_ref: ${{ github.event.inputs.head_ref }}
          pr_number: ${{ github.event.inputs.pr_number }}

      - name: Stop Review
        uses: andersinno/kolga-review-cleanup-action@v2
        with:
          namespace: ${{ env.K8S_NAMESPACE }}

